boundless-xyz/boundless

crates/order-generator/Cargo.toml
crates/order-generator/src/bin/zeth.rs
dockerfiles/order_generator_zeth.dockerfile

By default building zeth requires docker in order to create a reproducible build of the guests. This means that when building order-generator-zeth in docker, the build process then tries to spawn Docker within Docker when it compiles zeth. Docker within Docker [is not recommended](https://stackoverflow.com/a/33003273), and requires Docker to be run in privileged mode which causes problems for our deployments. 
Also fixing a bug where the Zeth build would fail, reducing the number of retries remaining, but the call to getBlock would succeed which resets the retry count to 0, causing the task to loop forever.

BM-535: Disable docker build for order-generator-zeth, fix retry bug

---

contracts/test/types/Offer.t.sol

Recently, foundry-toolchain did an update that required to set `allow_internal_expect_revert` to true in one of our test (see: https://book.getfoundry.sh/cheatcodes/expect-revert#error)

BM-540: Set allow_internal_expect_revert

---

crates/broker/src/rpc_retry_policy.rs

As shown in BM-542 some connection reset errors were not being correctly picked up and retried by the retry layer. This adds an extra match for detecting these and a test showing it should catch the specific error that issues highlighted

BM-542: Add an extra condition to catch connection reset errors in retry layer

---

crates/broker/src/config.rs
crates/broker/src/submitter.rs

Previously if a batch submission transaction failed for any reason (e.g. a connection reset on the RPC) the broker would never attempt to resubmit the batch and all tasks in that batch would fail.
This adds some resilience by adding a configurable parameter for number of attempts to resubmit a batch. Batches that fail will retry for the given number of attempts before setting their status to Failed.
- Adds new config field for BatcherConfig - max_submission_attempts (default=3)
- Adds test for multiple retries timing out
> Note: This solution avoids storing the number of submission attempts in the DB and so is not resilient to failures that trigger a panic and restart. In this case the batch will still be dropped. If this comes up as in issue in the future we can move the storage of …

BM-569: Add retries for batch submission

---

crates/order-stream/src/lib.rs
crates/order-stream/src/order_db.rs
crates/order-stream/src/ws.rs
justfile

There is an edge case currently where a broker address will be marked in the db as connected, even though there is no active websocket connection.
There are at least a few ways this could have happened:
- Write to DB to lower the connections failed
- Get balance on chain failed, panicked, which does not update the db for that pending connection
- Service crashed for some other reason, and these marked connections in the db aren't handled in this case
Decided to just simplify the logic such that all the data around pending connections is just kept in memory, as there doesn't seem to be any reason to persist it. I kept the pending connections in a separate map to reduce lock contention on the actual connections (don't want people spamming to DOS the active connections). The logic also is …

BM-565: fix: order stream connections mapping

---

crates/broker/src/provers.rs

Prompted by connection reset by bonsai status poll error. This retry is currently done in preflight, but not done in the actual proving call. This abstracts the logic to be used with both.

BM-567: fix: retry temporal bonsai poll errors

---

crates/order-stream/src/lib.rs
crates/order-stream/src/ws.rs

The issue was that previously on a failed upgrade, the pending connection was never removed or logged, so users could get in a state that rejected all future requests. 
This change adds a timeout to the pending connections such that if a request is made outside of the timeout window, it retries again, so that this doesn't get rejected permanently. This also adds a log on failure such that there is more information about failed upgrades.

BM-581: order-stream: fix pending connections and add timeout

---

contracts/src/BoundlessMarket.sol

A very minor change I made in the process of making other changes. I don't think there is any reason to have a `fillsLength` vairable in `fulfillBatch` when `fills.length` can be used instead. Benchamrks show no difference in gas cost.

BM-602: Remove fillsLength variable; no effect on gas cost

---

crates/boundless-market/src/order_stream_client.rs
crates/order-stream/src/lib.rs
crates/order-stream/src/ws.rs

Adds a configurable ping time to order stream client. Avoiding creating a separate public API for this to avoid breaking changes to include polling time.
Refactors the order stream integration test to handle multiple websocket connections and disconnection and receiving orders through that websocket.
Also simplifies the ws handler to not spawn and manage tasks. I assume this might have been done to allow cancellable tasks, but this seems unnecessary.

BM-607: Implement order stream client ping

---

crates/boundless-market/src/contracts/boundless_market.rs
crates/broker/src/config.rs
crates/broker/src/order_monitor.rs

Closes #390 
- Adds new public method to `boundless_market` - `with_stake_balance_alert` which takes a warning and error threshold to alert on
- Adds new config fields to broker to set these on the market in `order_monitor`
- Adds to existing test to check that market is correctly alerting when stake balance goes below thresholds

BM-621: Add configurable warnings and error logs for stake balance

---

bento/crates/workflow-common/src/lib.rs
bento/crates/workflow/src/tasks/executor.rs
bento/crates/workflow/src/tasks/keccak.rs

The error would panic and crash the instance, which was indefinitely irrecoverable. This rejects that invalid case, such that the node will continue.
The part I am unsure about is the sanity check within the executor for keccak requests. This changes to error log and skip those requests, and didn't seem like a clean mechanism to fail to proof as a whole, but perhaps this should still go through to fail with the prove agent so that it errors and then perhaps the tasks get cancelled through taskdb? Haven't looked that in depth at the implications yet.

BM-626: Fix bento crash with zero keccak input request

---

crates/broker/src/bin/broker.rs
crates/broker/src/order_monitor.rs

- Addresses silent failure on parsing highlighted in https://github.com/boundless-xyz/boundless/pull/321#discussion_r1999323451

BM-658: Add proper error handling for eth value string parsing failure

---

broker.toml
crates/broker/src/config.rs
crates/broker/src/db/fuzz_db.rs
crates/broker/src/db/mod.rs
crates/broker/src/order_picker.rs

Solves part of BM-598 in that we need multiple ways to limit the capacity of orders taken on by the broker, and limiting the amount of current locks is not a perfect solution but a reasonable mechanism that would be useful in the short term or to limit risk.
Will open PR for review once more thoroughly tested and will try to make sure no edge cases and minimimal overhead. Basically how this works is querying the database for orders that have been selected to be locked but not fulfilled, and then spawning tasks to handle pricing each. The capacity is calculated on an interval, every 10s, where the config and db will be checked, which will pick up when orders are fulfilled and more capacity available. Whenever pricing successful, it will reduce from the capacity to avoid extra tasks from …

BM-598: Limit concurrent locked orders

---

Cargo.lock
crates/boundless-market/src/contracts/mod.rs
examples/counter/Cargo.lock

This update contains the default selector for a FakeReceipt's seal as 0xFFFFFFFF

BM-668: Bump `risc0-ethereum` to 1.4.3

---

.github/workflows/contracts.yml
Cargo.lock
crates/boundless-market/Cargo.toml
foundry.toml

For some reason the `out` field of the `profile.reference-contract` in the `foundry.toml` does not get used. This PR forces its usage with the env var `FOUNDRY_OUT`
It also fixes a crate version mismatch, `risc0-groth16` by pinning and forcing to use a specific version. This can be removed once upgrading the zkvm to v2.0

BM-688: use FOUNDRY_OUT env var

---

crates/broker/src/order_picker.rs

If the test is very slow, this can report a different timing than tested. Didn't think it would be feasible for this test, but https://github.com/boundless-xyz/boundless/actions/runs/14178716715/job/39719682612?pr=458

BM-706: avoid edge case in broker capacity test

---

crates/broker/src/storage.rs

This cache is only used for requesting assessor and set builder images, and given they are IPFS URLs, probably fine to force the cache usage.
Perhaps not ideal if we switch this to a URL that isn't content addressed, but I don't think we ever plan to do this.

BM-739: update http cache to always use cached response

---

infra/order-stream/components/order-stream.ts
infra/util/index.ts

Now that Chain ID is in the stack name, it ends up repeated in the service name. This causes prod to fail, since now the names of various resources exceed the character limits.

BM-746: Shorten naming of order-stream resources

---

infra/order-stream/components/order-stream.ts
infra/order-stream/index.ts

Now that the cert has been created and validated, we can enable the order stream is prod to use it.
ACM_CERT_ARN is not necessary as in this design the cert is fully managed by Pulumi, so we can get the ARN from the Pulumi resource.
This should be the last change to set up the DNS, though I'm unable to test locally since this is prod only, so can't be sure.

BM-757: Use cert in prod

---

dockerfiles/agent.dockerfile

Building the docker image results in the following error:
```console
=> ERROR [exec_agent builder 8/8] RUN     --mount=type=secret,id=ci_cache_creds,target=/root/.aws/credentials     --mount=type=cache,target=/root/.cache/scc  0.4s
------
> [exec_agent builder 8/8] RUN     --mount=type=secret,id=ci_cache_creds,target=/root/.aws/credentials     --mount=type=cache,target=/root/.cache/sccache/,id=bndlss_agent_sc     source ./sccache-config.sh shared/boundless/rust-cache-docker-Linux-X64/sccache &&     cargo build --release -p workflow -F cuda --bin agent &&     cp /src/bento/target/release/agent /src/agent &&     sccache --show-stats:
0.169 Using local sccache
0.178 error: toolchain '1.85-x86_64-unknown-linux-gnu' is not installed
0.178 help: run `rustup toolchain install …
```

BM-776: Bump rust toolchain version in agent.dockerfile

---

infra/order-generator/Pulumi.prod.yaml
infra/order-generator/Pulumi.staging.yaml

We saw a large spike in gas prices that made our order generator orders not profitable. These orders are used to assess the health of the system, so its important they are always fulfilled. Bumping the max price should help keep these order fulfillable during gas spikes.

BM-777: Raise max price for order gens

---

dockerfiles/agent.dockerfile

Building the docker image results in the following error:
```console
=> ERROR [exec_agent builder 8/8] RUN     --mount=type=secret,id=ci_cache_creds,target=/root/.aws/credentials     --mount=type=cache,target=/root/.cache/scc  0.4s
------
> [exec_agent builder 8/8] RUN     --mount=type=secret,id=ci_cache_creds,target=/root/.aws/credentials     --mount=type=cache,target=/root/.cache/sccache/,id=bndlss_agent_sc     source ./sccache-config.sh shared/boundless/rust-cache-docker-Linux-X64/sccache &&     cargo build --release -p workflow -F cuda --bin agent &&     cp /src/bento/target/release/agent /src/agent &&     sccache --show-stats:
0.169 Using local sccache
0.178 error: toolchain '1.85-x86_64-unknown-linux-gnu' is not installed
0.178 help: run `rustup toolchain install …
```

BM-776: Bump rust toolchain version in agent.dockerfile (#523)

---

infra/slasher/Pulumi.prod.yaml
infra/slasher/Pulumi.staging.yaml

We operate a slashing bot on the Boundless testnet, and due to difficulties with the freezing system that ultimately would cause requestors to have a bad experience, we temporarily removed RISC Zero provers from the list of slashing targets. We have not removed freezing, and so now will slash our own provers again.

BM-772: Resume slashing RISC Zero provers using the RISC Zero slasher

---

infra/slasher/index.ts

```
error: a value is required for '--skip-addresses <SKIP_ADDRESSES>' but none was supplied
```
Currently deploying an instance to dev account to test, but this should fix.

BM-784: Fix skip address empty

---

crates/boundless-cli/src/bin/boundless-cli.rs

Currently when these don't match its difficult to debug in the CLI.

BM-791: Print predicate and journal on mismatch

---

infra/pipelines/components/notifications.ts
infra/pipelines/index.ts

We had some missing notifications yesterday. I've solved the issue (was just a misconfiguration in Slack), but this PR sets up logging and a DLQ for notifications that will help debug future issues.

BM-787: Configure logging for notification delivery

---

crates/boundless-cli/src/bin/boundless-cli.rs
documentation/site/pages/developers/tooling/cli.mdx

**Syntax**:
```
proving lock --request-id <U256> [--request-digest <B256>] [--tx-hash <B256>]
[--order-stream-url <URL>]
```
- `--request-id`: the proof request identifier.
- `--request-digest`: request’s EIP712 digest (optional).
- `--tx-hash`: transaction hash (optional, to find the request).
- `--order-stream-url`: fetch request data from an offchain server.
**Example**:
```
boundless-cli proving lock --request-id 0x5...
```
Should results in something like:
```console
2025-04-17T17:41:00.519190Z  INFO test_proving_offchain: boundless_cli: Locking proof request 0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc00000001
2025-04-17T17:41:00.522179Z DEBUG test_proving_offchain: boundless_cli: Fetched order details: ProofRequest { id: 1477785848920527538943426201171954208394474144316077899777, …
```

BM-792: Add lock subcommand

---

crates/order-stream/src/api.rs
infra/order-stream/Pulumi.prod-11155111.yaml
infra/order-stream/Pulumi.staging.yaml
infra/order-stream/components/order-stream.ts
infra/order-stream/index.ts

We noticed the order stream deployments had rolled back and were marked as unhealthy. Root cause was that the health check endpoints in Pulumi were not updated to include the new /v1/ versioning of the API. Deployments still succeed in this case, as Pulumi does not have insight into whether a container's healthchecks succeed or not.
Also adds an alarm so we can be notified of this in the future, and sets up slack alerts for the order stream which was missed.

BM-794: Fix order stream deployment healthcheck

---

crates/order-generator/src/bin/zeth.rs
crates/order-generator/src/main.rs

Missing parenthesis included in a last minute change that intended to add a 10% margin on gas price estimation resulted in reduction instead.

BM-804: Fix simple gas estimation in order generator

---

infra/prover/broker-prod.toml
infra/prover/broker-staging.toml

With Bonsai as our proving engine, the current parameters are overly conservative. Increasing the peak prove hz and the max locks, these parameters should still be quite conservative.

BM-820: Increase capacity for Bonsai-backed broker in staging and prod

---

infra/pipelines/pipelines/prover.ts

Seeing `signal: 9, SIGKILL: kill` during compilation of the broker in the pipeline. This implies out of memory. Bumping the instance size.

BM-821: Bump prover builder pipeline memory

---

infra/prover/index.ts

Rename EFS file system with `-rev2` tag to cause the Pulumi to recreate it in the code pipeline.

BM-824: Create revision 2 EFS for prover

---

infra/pipelines/pipelines/order-stream.ts

Now that we handle order-stream outages in the prover, we should be safe to move back to CD.
This reverts commit fa277510fc08949472cb92f977a05fe8ed980a11.

Revert "BM-744: Disable CD on order-stream (#494)"

---

crates/broker/src/order_picker.rs

We've seen a few of these errors recently, but we're not logging the underlying error, so unclear if they are 500s or rate limiting. This should help debug

BM-828: Log error on image fetch fail

---

.github/workflows/linear.yml
.github/workflows/main.yml

When making changes to infra or docs in particular, there is no need to build and test the core Rust and Solidity code base. In promotion of making more frequent, smaller PRs, that clear CI faster, this PR updates the path filters to allow those PRs to merge without the main codebase test suite.

BM-825: Update path filtering on CI to speed up PRs with changes to docs or infra

---

infra/prover/index.ts

https://github.com/boundless-xyz/boundless/pull/542 includes breaking changes to the DB. In order to deploy this, we need to update the EFS volume name to trigger Pulumi to recreate it.

BM-835: Update Pulumi EFS volume name to `rev3` to recreate DB

---

request.yaml

Current example uses 5 HP, which is higher than most or all of the provers on Sepolia use in their configs.

BM-836: Update example `request.yaml` to 0.1 HP

---

crates/broker/src/order_monitor.rs
crates/broker/src/order_picker.rs

There was an underflow in the log if the estimation is before the current time. This seems like a reasonable place to warn, as it indicates that the broker may overlock orders. Possibly could be noisy if tuned tightly, but airing on the side of caution. Happy to only warn if above a margin of error also

BM-840: fix logic with estimation log and warn if broker behind

---

crates/boundless-market/src/contracts/boundless_market.rs

Closes #547
Given this is only retrying one part of the transaction, didn't make sense to make this another config value in the broker.toml, but open to an argument that it should be -- just trying to avoid the config bloat.
I also added this retry to other calls, given it's relatively a more common error case that leads to other issues. This only does retries in the case where the RPC indicates that a tx is finalized _and_ doesn't return the receipt as a result, so doesn't slow down failure cases.

BM-852: add retry on getting receipt from confirmed transaction

---

infra/prover/index.ts

`order_picker=trace` was added to debug an issue, and is no longer needed.

BM-870: Remove order picker trace logging from deployed prover

---

infra/prover/index.ts
infra/slasher/Pulumi.prod.yaml
infra/slasher/Pulumi.staging.yaml

Lock Failed Alarms: Both these are expected when someone else beats us to locking the request. No need to alert on them.
re: hyper_util, I moved the slasher logging to debug to debug the SQL issue. On debug mode hyper_util logs "error" when a connection is closed, which triggers our alarms, so moving it back to info.

BM-874: Remove lock failed alarms, lower hyper_util log level

---

crates/boundless-market/src/contracts/boundless_market.rs
crates/broker/src/order_monitor.rs
crates/broker/src/submitter.rs

* The SDK also does a check if the request is locked which was not caught in the prover, meaning it triggers alarms. Now we map this error to a known error.
* The error codes in the submitter were not being rendered correctly. Also changed some logs to warning since we retry submission. Now we only error log after the retries all fail so they don't trigger alarms

BM-882: Catch locked already error from sdk, fix error codes in submitter

---

crates/boundless-market/test-utils/src/lib.rs
examples/composition/apps/src/main.rs
examples/counter-with-callback/apps/src/main.rs
examples/counter/apps/src/main.rs
examples/smart-contract-requestor/apps/src/main.rs

Not quite ideal to have different gas estimation logic for testing, but currently unclear if based around anvil or if there is some edge case that can be hit that changes the gas usage. This is a stop-gap to avoid random failures in tests, as this has not been seen outside of tests yet. 👀 
Also changes the invocations of `BrokerBuilder::new_test` to keep around the config file handle so it isn't dropped and causes error logs within the tests.

BM-891: multiply anvil gas estimates in testing contexts

---

crates/boundless-market/src/contracts/boundless_market.rs
crates/broker/src/chain_monitor.rs
crates/broker/src/order_monitor.rs
infra/prover/index.ts

Moves RPC errors in the chain monitor to known, and tx confirmation errors to known.
Both these errors will happen occasionally transiently. We only need to be alerted if they are happening frequently

BM-899: Chain monitor RPC errors as known. Order monitor txn confirmation errors as known.

---

Cargo.lock
crates/broker/src/market_monitor.rs
crates/guest/assessor/assessor-guest/Cargo.lock
examples/composition/Cargo.lock
examples/counter-with-callback/Cargo.lock
examples/counter/Cargo.lock
examples/smart-contract-requestor/Cargo.lock

Event delivery has at least once semantics. This was handled for
RequestSubmitted event, but not for RequestLocked or RequestFulfilled.

Backport "BM-880: Handle double event delivery in RequestSubmitted and RequestLocked (#612)" to release

---

justfile

I realized that `just check` does not always error on issues that will fail on the `clippy` job in CI. This PR adds the `RUSTFLAGS=-Dwarnings` flag to the `justfile` to mirror CI.

BM-911: Add RUSTFLAGS=-Dwarnings in justfile to mirror CI

---

crates/indexer/migrations/1_transactions.sql
crates/indexer/src/db.rs
crates/indexer/src/lib.rs

The indexer was calling too many times get_block_by_number, to get its timestamp.
This PR adds a blocks table to store the block timestamp, whenever there is a cache miss and attempt to retrieve it from the db whenever the timestamp for a block is required.
Moreover refactor the starting block logic so that if the starting block is set, use the maximum of the starting block and the last processed block; otherwise, use the last processed block if it is greater than 0, or the current block if the last processed block is 0. This is to ensure that we don't process blocks that have already been processed and to avoid processing blocks that are in the future.
It also tune down the log level

BM-921: Improve indexer

---

crates/indexer/migrations/1_transactions.sql
crates/indexer/migrations/6_blocks.sql
crates/indexer/src/lib.rs

should fix:
```
2025-05-15T16:16:16.323327Z  WARN boundless_indexer: Failed to process blocks from 8038641 to 8333060: EventQueryError(TransportError(ErrorResp(ErrorPayload { code: -32602, message: "Log response size exceeded. You can make eth_getLogs requests with up to a 500 block range and no limit on the response size, or you can request any block range with a cap of 10K logs in the response. Based on your parameters and the response size limit, this block range should work: [0x7aa8f1, 0x7d5efc]", data: None }))), attempt number 11, retrying in 120s
```

BM-924: Cap block range size on the indexer

---

crates/indexer/src/main.rs
crates/order-generator/src/main.rs
crates/order-stream/src/bin/order_stream.rs
crates/slasher/src/main.rs
infra/order-generator/Pulumi.prod.yaml
infra/order-generator/Pulumi.staging.yaml
infra/order-generator/components/order-generator.ts
infra/order-generator/index.ts
infra/order-stream/components/order-stream.ts
infra/slasher/index.ts

Noticed that the off-chain order generator has been crashing but not alarming us. The error alarm there was misconfigured, so fixed that. But also noticed we don't have alarms for when ecs tasks error out and exit. Added those to all services.
Reason for off-chain order generator crashing is that it creates orders with a high max price (e.g. > 10 ETH) and didn't have enough balance on the market to submit the request. The auto deposit feature was set too low to cover this, so increased it to 20 ETH.
I haven't tested this as this would require redeploying every service, but fairly sure it should be ok ..

BM-926: Add fatal log on process exit, and alarms. Fix order generator topup

---

infra/builder/configure_builder.sh
infra/indexer/components/indexer.ts
infra/indexer/index.ts
infra/order-generator/components/order-generator.ts
infra/order-stream/components/order-stream.ts
infra/prover/index.ts
infra/slasher/index.ts

When we change secrets a new ECS deployment is not triggered. This is because changing the secret updates the value stored in Secret Manager, but ECS only sees the Secret Arn, not the secret itself, so it doesn't know it needs to redeploy.
To fix we pass a hash of the secrets as an env variable. Changes in env variables _do_ trigger a redeployment.

BM-931: Redeploy ECS tasks when secrets updated

---

crates/indexer/src/db.rs

This PR is a sort of hack for fixing the Indexer crashing after failing to process a slashed event.
In case the DB has gaps, it might happen that when processing a slash event the corresponding locked event is missing.
In that case we just return the Address::ZERO as prover address

BM-933: Fix missing locked event on the Indexer

---

crates/indexer/src/db.rs
infra/indexer/Pulumi.staging.yaml
infra/indexer/components/alarms.ts
infra/indexer/components/indexer.ts
infra/indexer/components/monitor-lambda.ts
infra/indexer/components/rust-lambda.ts
infra/indexer/index.ts
infra/order-generator/components/order-generator.ts

- Currently metrics are being emitted under 3 different namespaces, simplifying to two, and hooking up the alarms with the metrics
- Changing logs to output sql errors
- Fixes naming of infra to have chain ID for consistency with other services, and to avoid conflicts when we go multichain
- Removing circuit breaker on ECS service that causes it to stop trying to start up after a few failures
- Adding FATAL alarm for when the indexer exits and stops running
Does NOT fix the current bug in staging:
```
2025-05-15T19:21:07.614-04:00
2025-05-15T23:21:07.614174Z ERROR boundless_indexer: Failed to process blocks from 8334235 to 8334735: DatabaseError(SqlErr(RowNotFound))
40
2025-05-15T19:21:07.574-04:00
2025-05-15T23:21:07.574340Z DEBUG boundless_indexer: Processing slashed event for request: …
```

BM-930: Indexer namespace cleanup, various fixes

---

README.md
crates/indexer/migrations/3_proof_requests.sql
crates/indexer/migrations/7_proof_request_metadata.sql
crates/indexer/src/db.rs
crates/indexer/src/lib.rs
crates/indexer/tests/basic.rs
crates/ops-lambdas/indexer-monitor/src/handler.rs
crates/ops-lambdas/indexer-monitor/src/monitor.rs
infra/indexer/Pulumi.prod-11155111.yaml
infra/indexer/Pulumi.staging.yaml
infra/indexer/alarmConfig.ts
infra/indexer/components/indexer.ts
infra/indexer/index.ts

* We're seeing alerts going off like "no requests submitted in 15 mins" when our order generators submit every 5 minutes. Adding additional logging of ids to help debug.
* Also making the alerts more lenient just to reduce noise for now until the issue is resolved.
* Changing fulfilled monitoring to use event emission time over `biddingStart`. Since fulfillment can happen a long time after `biddingStart`, I believe the previous implementation can cause us to miss capturing fulfillment events.
* Removing SEV1s from staging. SEV1 will page us and we only want to do that for prod.

BM-942: Indexer alerts on event time rather than bidding start. Additional logging.

---

crates/ops-lambdas/indexer-monitor/src/handler.rs
crates/ops-lambdas/indexer-monitor/src/main.rs
crates/ops-lambdas/indexer-monitor/src/monitor.rs
infra/prover/components/bentoBroker.ts
infra/prover/components/bonsaiBroker.ts
infra/prover/components/brokerAlarms.ts

* Errors in the lambda monitor are being swallowed as we map the error to a string
* Fix some issues with the SQL queries in the monitor
* Prover deploy is failing due to a change in how we create the log group. Fixing this.

BM-948: Propagate logs for monitor failures. Fix monitor queries. Fix prover deploy

---

infra/prover/components/bonsaiBroker.ts

Staging error:
```
Diagnostics:
aws:cloudwatch:LogGroup (staging-bonsai-prover-11155111-log-group):
error: inputs to import do not match the existing resource: [skipDestroy]
```

BM-949: Fix log group

---

broker.toml
crates/broker/src/config.rs
crates/broker/src/submitter.rs
infra/prover/broker-dev.toml
infra/prover/broker-prod.toml
infra/prover/broker-staging.toml
infra/prover/components/brokerAlarms.ts

The transactions in the submitter can occasionally fail due to not being confirmed in time. Given those transactions the same treatment as we have for sending lock transactions, which is currently only alert us on 3 errors in an hour.
Also changing the default retries for batch submission down to 2. Generally if a single retry here doesn't work a 3rd won't work either, and retrying too much wastes time + gas

BM-950: Tx timeouts in submitter as known errors

---

Cargo.lock
Cargo.toml
crates/guest/assessor/assessor-guest/Cargo.lock
examples/composition/Cargo.lock
examples/counter-with-callback/Cargo.lock
examples/counter/Cargo.lock
examples/smart-contract-requestor/Cargo.lock

With the release of 0.8.0, the version under development is now 0.9.0. This bumps the version on `main`

BM-953: Bump development version to 0.9.0

---

documentation/site/pages/provers/quick-start.mdx

- bump prover quick start to point to `release-0.8`
- found that the missing link to deposit instructions is jarring when setting up a prover

BM-957: 0.8 bump + obvious link to deposit HP to market

---

scripts/setup.sh

I noticed when running a prover on a fresh machine, that we recommend you run the setup script, and then we ask to run a lot of different `just` commands. If you're running this on a fresh machine, the script handily installs Rust, and Docker and Nvidia etc. dependencies for you, but not the `just` command runner.
It felt like it was missing, so I added it to the `setup.sh` script and verified it worked on an Ubuntu 22.04 install.

BM-958: add just installer to prover setup script

---

crates/ops-lambdas/indexer-monitor/src/handler.rs
crates/order-stream/src/lib.rs
infra/indexer/Pulumi.prod-11155111.yaml
infra/indexer/alarmConfig.ts
infra/order-stream/Pulumi.prod-11155111.yaml
infra/order-stream/Pulumi.prod-8453.yaml
infra/order-stream/Pulumi.staging.yaml
infra/order-stream/components/order-stream.ts
infra/order-stream/index.ts
infra/prover/components/bentoBroker.ts

* Currently you need 1 trillion USDC deposited to connect to the order stream due to the decimal difference. Adjusted it to 5 USDC.
* Changing the top level fulfillment and expired alarms. We are testing in staging/prod and seeing these alarms triggered frequently
* Splitting Bento logs from Broker logs in the Bento Broker cloudwatch logs groups
* Also making the logs on the monitor easier to parse

BM-980: Fix order stream ws stake requirement. Adjust alerts and logs

---

crates/broker/src/market_monitor.rs
crates/order-generator/src/main.rs
infra/order-generator/Pulumi.prod-11155111.yaml
infra/order-generator/Pulumi.prod-8453.yaml
infra/order-generator/Pulumi.staging.yaml
infra/order-generator/components/order-generator.ts
infra/order-generator/index.ts
infra/prover/components/brokerAlarms.ts
infra/slasher/Pulumi.prod-11155111.yaml
infra/slasher/Pulumi.prod-8453.yaml
infra/slasher/Pulumi.staging.yaml
infra/slasher/index.ts

* Changed Market monitor event poll error to unexpected. Currently a single rpc error here is unexpected, wrapping in an error code with a higher threshold
* Added balance alerts for order gens and slasher. As part of this also changes auto deposit to not error out on fail, since now we have balance alerts that will tell us when eth balances are low
* Slightly scaled down max mycle price for the order gens on Sepolia. We're going through sepETH fast

BM-990: Event poll error to unexpected, balance alerts for order gens / slasher, scale down sep OG pricing

---

infra/util/index.ts

Rather than restrict all names, instead when creating s3 buckets we should use shorter names.

Remove service name length restriction

---

compose.yml

- Removes misleading commented out code (avoid suggesting to use coproc/join streams)
- Changed CPU limit to 300% (still overkill since should be max 2 threads)
- Added second exec agent by default
- A lot of relative exec load, this should be a more reasonable default, make it easier to add/remove agents

BM-1148: update to use 2 exec agents by default

---

compose.yml

I made this change in another PR, somehow it got reverted in a merge update it seems

BM-1158: simplify exec agent config in compose

---

crates/broker/src/proving.rs
crates/broker/src/reaper.rs
crates/broker/src/utils.rs

Shouldn't matter too much with reaper changes, but also simplifies some code. Avoids calling cancel unless the order is in the proving state, to avoid calling cancel on a completed proof.

BM-1157: only cancel proof on proving order status

---

infra/prover/components/bentoBroker.ts

Increases timeout to 2h for stop (graceful)
Also makes explicit the terminate signal (that is the default, just making sure it doesn't change in future)

BM-1185: increase systemd stop timeout

---

compose.yml

This was removed from the exec agent because it didn't seem necessary, but it seems it is needed for some environments

BM-1197: include nvidia runtime with all agents

---

documentation/site/pages/provers/broker.mdx

Not needed with reaper and expiry timeouts/checks that now exist

BM-1198: remove old debugging stuck orders docs

---

crates/broker/src/proving.rs

Currently the logic is handled such that if a proof is being generated within the retry, it will create a new stark session on the next retry. This can cause cascading failures due to not matching the estimation logic.
Ideally in future it would be nice to estimate if we can create a new session and try if possible, but would require a larger refactor.

BM-1206: Avoid creating new proving sessions on retry

---

crates/broker/src/lib.rs
crates/broker/src/order_picker.rs

Right now most fulfill after expiry orders are just being ignored and hitting that previously confusing log:
```
INFO broker::order_picker: Removing order with request id 2546c553d857d20658ece248f7c7d0861a2406818b2830f9 because it's exec limit is below 0 cycles
```
This fixes that as it was using eth denom for stake and also losing precision on the calculation.

BM-1208: fix stake denom, avoid precision loss, clean up logs in picker

---

documentation/scripts/check-links.ts
documentation/site/pages/developers/quick-start.mdx
documentation/site/pages/developers/smart-contracts/verifier-contracts.mdx
documentation/site/pages/developers/steel/history.mdx
documentation/site/pages/developers/tutorials/request.mdx
documentation/site/pages/developers/tutorials/sensitive-inputs.mdx
documentation/site/pages/provers/broker.mdx
documentation/site/pages/provers/performance-optimization.mdx
documentation/site/pages/provers/proving-stack.mdx
documentation/site/pages/provers/quick-start.mdx

fixing dead link on /developers/quick-start page that @nahoc pointed out, I looked into adding a link checker. Quickly, I realized there is already a link checker in `documentation/scripts/check-links.ts`, but clearly wasn't working as intended. 
Looking in there, it only checks `.md` files and not `.mdx` files which is what we use so only the README.md was being checked. 
This PR addresses this, and fixes the script; and fixes all the dead links the scripts finds so that the CI passes :)

BM-1213: fix dead links (hopefully forever)

---

crates/broker/src/order_monitor.rs
crates/broker/src/order_picker.rs
infra/prover/components/brokerAlarms.ts

We've seen some RPC errors when getting wallet balances that are currently Unexpected errors. Catching them and setting a higher threshold.
Also raising the threshold on the market error alert in the submitter. We retry in the submitter and often see recovery from those errors, so no need to alert unless it fails multiple times.

BM-1225: Make RPC errors in monitor/picker known. Raise threshold for submitter alarms

---

infra/prover/tomls/bento/broker-prod-11155111.toml
infra/prover/tomls/bento/broker-prod-8453.toml
infra/prover/tomls/bento/broker-prod-84532.toml
infra/prover/tomls/bento/broker-staging-11155111.toml
infra/prover/tomls/bento/broker-staging-84532.toml
infra/prover/tomls/bonsai/broker-prod-11155111.toml
infra/prover/tomls/bonsai/broker-prod-8453.toml
infra/prover/tomls/bonsai/broker-prod-84532.toml
infra/prover/tomls/bonsai/broker-staging-11155111.toml
infra/prover/tomls/bonsai/broker-staging-84532.toml

We dropped min_deadline in order to get lower latency orders being fulfilled, but forgot to drop this one. May be too low, but we'll test with this and revert if necessary

BM-1230: Drop SNARK min buffer

---

crates/broker/src/order_picker.rs

Some were previously updated in https://github.com/boundless-xyz/boundless/pull/809/files, but missed this one.

BM-1240: avoid precision loss in min/max mcycle price calculations

---

Cargo.lock
Cargo.toml
crates/guest/assessor/assessor-guest/Cargo.lock
crates/guest/util/echo/Cargo.lock
crates/guest/util/identity/Cargo.lock
crates/guest/util/loop/Cargo.lock
examples/composition/Cargo.lock
examples/counter-with-callback/Cargo.lock
examples/counter/Cargo.lock
examples/smart-contract-requestor/Cargo.lock

Bump risc0-ethereum version 2.2.1, which includes a reduction of the default event query range to avoid errors when using Alchemy free tier (https://github.com/risc0/risc0-ethereum/pull/625)

BM-1251: Bump risc0-ethereum version to 2.2.1

---

crates/broker/src/aggregator.rs
infra/prover/tomls/bento/broker-prod-11155111.toml
infra/prover/tomls/bento/broker-prod-8453.toml
infra/prover/tomls/bento/broker-prod-84532.toml
infra/prover/tomls/bento/broker-staging-11155111.toml
infra/prover/tomls/bento/broker-staging-84532.toml

Dialing this back a little bit as we are seeing increased errors. Compressing can take close to 2 minutes in worst case for our Bento broker

BM-1238: Bump block_deadline_buffer_secs

---

crates/broker/src/order_picker.rs

This check could likely also be removed, if we trust the execution cap limits, but keeping for now unless someone indicates otherwise

BM-1269: remove skip order on priority above mcycle limit

---

compose.yml

Increases the default TTL to 16 hours to give more breathing room for larger jobs

BM-1285: Increase default redis TTL in bento

---

infra/prover/tomls/bento/broker-staging-84532.toml
infra/prover/tomls/bonsai/broker-prod-11155111.toml
infra/prover/tomls/bonsai/broker-prod-8453.toml
infra/prover/tomls/bonsai/broker-prod-84532.toml
infra/prover/tomls/bonsai/broker-staging-11155111.toml
infra/prover/tomls/bonsai/broker-staging-84532.toml

Additionally, this updates the priority and deny lists for the staging brokers to use a deployment of the Signal contract that targets staging.

BM-1301: Adjust min price and peak kHz parameters for Bonsai Broker

---

crates/boundless-cli/src/bin/boundless-ffi.rs
crates/boundless-cli/src/bin/boundless.rs
crates/boundless-cli/src/lib.rs
crates/boundless-market/src/client.rs
crates/boundless-market/src/contracts/boundless_market.rs
crates/boundless-market/src/order_stream_client.rs
crates/indexer/tests/basic.rs
crates/slasher/tests/basic.rs

The `Order` struct used throughout the code base makes a bad assumption that all signatures are ECDSA, and can be parsed by `alloy`. Signatures should not be parsed, and instead should be handled as bytes expect where they are verified. Fixing this issue is a much deeper refactor, but this PR starts by refactoring the method to fetch an order from the market, with the immediate goal of supporting handling of ERC1271 authorized requests in the `boundless` CLI.

BM-1307: Support fetching of ERC-1271 authorized requests in `boundless` cli

---

crates/order-stream/src/lib.rs

Our CPU/memory utilization shows as around 5%, so this should be safe with our current instance size.

BM-1334: Bump order stream maxconns to 1000

---

documentation/site/pages/provers/broker.mdx
documentation/site/pages/provers/requirements.mdx

- added a little bit more info for the 'allow_client_addresses' and 'peak_prove_khz' options

BM-1329: add more info to broker.toml descriptions

---

infra/distributor/Pulumi.prod-11155111.yaml
infra/distributor/Pulumi.prod-84532.yaml
infra/distributor/Pulumi.staging-11155111.yaml
infra/distributor/Pulumi.staging-84532.yaml
infra/prover/components/bonsaiBroker.ts

Few fixes for staging:
* The bonsai brokers are both erroring a lot with DB locked. Since its been a while since we monitored the staging brokers so its unclear what errors have built up in the DB and its general state, and since we want to move off EFS anyway to solve this issue once and for all, I propose we wipe the DB as a quick fix to get things rolling.
* One of the brokers is erroring due to low stake. This is happening due to the threshold for topping it up being too low in the distributor.

BM-1356: Wipe bonsai DB, increase threshold for topping up stake

---

broker-template.toml

Allows provers to evaluate signal proofs without being blocked by stake limits

BM-1357: Bump stake default

---

crates/ops-lambdas/indexer-monitor/src/monitor.rs
infra/indexer/alarmConfig.ts

This adjusts the lambda to check the timestamp of the fulfillment rather than the timestamp of the submission so that it gets counted within the window of what is checked. This part was an autogenerated change, but seems correct from looking it over.
I also increased the alert window from 30 mins to 60 as on graceful stop, re-compilation, and then a lock and fulfill, that is very tight. Hopefully reduces false positives.

BM-1363: Fix Ethereum Sepolia monitor success rate calculation

---

compose.yml
crates/guest/util/identity/Cargo.lock
crates/guest/util/identity/Cargo.toml

Looking at the diff https://github.com/risc0/risc0/compare/v2.3.0...v2.3.1 it seems not necessary to update our min version in our libraries to be this version. Feel free to share a reason why this might be necessary. (cc @capossele I know you suggested updating the cargo locked deps)

BM-1376: bump bento image to 2.3.1

---

crates/broker/src/lib.rs
crates/broker/src/order_monitor.rs
crates/broker/src/order_picker.rs
crates/broker/src/prioritization.rs

These changes are to prevent redundant executions when the lock and fulfill session limit is less than the fulfill after lock one and the exec hits session limits. Also refactors the logic of the session limit calculation, to try to simplify with this added complexity of calculating both limits

BM-1365: refactoring cycle limits

---

crates/broker/src/proving.rs

Given the proving failed, would have been helpful to log the bento/bonsai job ID to make debugging purposes easier

BM-1410: log job ID on proving failed log

---

crates/slasher/src/lib.rs

Avoid triggering alerts when the error is likely transient and will be retried. Once retries are exhausted we log at error level and trigger alerts.

BM-1452: Change error logs for retryable errors to warn

---

Cargo.lock
Cargo.toml
crates/broker/src/market_monitor.rs
crates/guest/assessor/assessor-guest/Cargo.lock
examples/composition/Cargo.lock
examples/counter-with-callback/Cargo.lock
examples/counter/Cargo.lock
examples/smart-contract-requestor/Cargo.lock

Resolves BM-1283
https://github.com/alloy-rs/alloy/pull/2755 changes the behavior such that the stream is closed when the filter is not found, so in this case we just re-create the subscription.

BM-1283: re-create filter on RPC provider drop

---

crates/distributor/src/main.rs
infra/distributor/Pulumi.prod-11155111.yaml
infra/distributor/Pulumi.prod-8453.yaml
infra/distributor/Pulumi.prod-84532.yaml
infra/distributor/Pulumi.staging-11155111.yaml
infra/distributor/Pulumi.staging-84532.yaml
infra/distributor/index.ts

The provers have accumulated a lot of stake, presumably by winning secondary auctions. Adding logic to distributor to withdraw that value so it can be redistributed.
Also fixing the thresholds on Base Mainnet. Currently when ETH balance drops below 0.02, they are only topped back up to 0.02, creating top-ups on every distributor run.
We also let prover stake balance drop to the point where they can't participate in big orders like Signal, so setting a higher threshold and top up value for stake, in case we need to start participating again.

BM-1449: Move accumulated stake from provers back to distributor. Adjust distributor thresholds for base mainnet

---

crates/broker/src/market_monitor.rs
crates/broker/src/offchain_market_monitor.rs
crates/broker/src/proving.rs
crates/broker/src/submitter.rs

Compacts the error log to be one-line so that it is easier to debug when grepping for the order/error
Docs on formats: https://docs.rs/anyhow/latest/anyhow/struct.Error.html#display-representations

BM-1465: change anyhow error logs to be one-line

---

infra/pipelines/Pulumi.prod.yaml
infra/pipelines/components/notifications.ts
infra/pipelines/index.ts

Moves alerts over to new Slack.
Sets up infra for existing mainnet beta alerts to go to:
#alerts-beta-boundless
#alerts-beta-boundless-staging
And sets up infra for our launch alerts to go to
#alerts-boundless
#alerts-boundless-staging

BM-1509: Migrate alerts to new slack and create channels for mainnet

---

crates/boundless-market/src/client.rs

This has made some debugging much more painful, fixing now before I forget

BM-1481: keep error context when input/program upload fails

---

crates/guest/povw/log-updater/Cargo.lock
crates/guest/povw/mint-calculator/Cargo.lock
crates/guest/povw/mint-calculator/src/main.rs
crates/guest/povw/src/mint_calculator.rs
crates/guest/povw/tests/mint-calculator.rs

Currently on `victor/povw` the reward cap is determined based on the value recipient. This allows recipients to exceed the available reward cap by splitting their work across multiple logs, and then producing multiple mint transactions. This circumvents the intention of the completeness checks to ensure that the cap is applied to the total rewards for the epoch.
To address this issue, this PR changes the mint calculator to apply the reward cap based on the work log ID. This aligns with the completeness checks to ensure the cap cannot be circumvented.
As an effect of this change, provers will need to delegate the reward power of their staked ZKC to the work log ID.

Cap rewards based on the log ID to prevent avoidance of the cap

---

crates/guest/povw/log-updater/src/main.rs
crates/guest/povw/tests/log-updater.rs

On `victor/povw`, there is an issue that is a prover specifies a value recipient of zero, they will not only burn the rewards for that update, but will be prevented from claiming rewards for any future update.
This PR fixes this by preventing a value recipient of zero from being specified. The check is added to the log builder guest, such that the update cannot be proven or posted to the PoVW Accounting contract.

Prevent the zero address from being used as value recipient

---

crates/broker/src/order_picker.rs

I forgot this error was matched so the new format triggered an alert and leads to different handling.

BM-1527: Handle new execution limit error in broker

---

bento/crates/workflow/src/tasks/join.rs
bento/crates/workflow/src/tasks/join_povw.rs
bento/crates/workflow/src/tasks/keccak.rs
bento/crates/workflow/src/tasks/prove.rs
bento/crates/workflow/src/tasks/union.rs

Add integrity checks to each phase of proving for better retry behavior.
tested with bento cli 1,2, and 19 segment counts

BM-1587: check each step before sending to redis

---

bento/crates/workflow/src/lib.rs

This removed the error context, which avoided the handling of the exec limit error on broker side. This formatting will also help readability for other errors.

BM-1602: format causes into bento err string

---

crates/boundless-cli/src/commands/povw/prepare.rs

The condition if !seen_log_ids.insert(info_log_id) was inverted.
HashSet::insert() returns:
- true if the value was not previously in the set (first time seeing this log ID)
- false if the value was already in the set (seen before)
Before: The warning was shown for every receipt with log ID 0, not just the first.
After: The warning is shown only once per unique log ID.

Fix log ID check to correctly insert seen IDs

---

.github/CODEOWNERS

Added @neutronmoderator as a code owner for the /docs/ directory.

BM-1685: Add @neutronmoderator to CODEOWNERS for /docs/
