boundless-xyz/boundless

- crates/order-generator/src/bin/zeth.rs
This commit got missed in my last PR. Fixes Zeth gen
> BM-566: Zeth order gen fix

- .github/actions/bininstall-risc0/action.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- bento/Cargo.lock
- bento/Cargo.toml
- bento/crates/workflow/Cargo.toml
- bento/crates/workflow/src/tasks/executor.rs
- bento/crates/workflow/src/tasks/keccak.rs
- crates/broker/src/config.rs
- crates/broker/src/provers.rs
- crates/broker/src/submitter.rs
- crates/order-stream/src/lib.rs
- crates/order-stream/src/order_db.rs
- crates/order-stream/src/ws.rs
- justfile
This includes the unreviewed #341 changes, but will update that commit when pulled in
> Backport broker fixes to release branch

- bento/crates/taskdb/migrations/2_optimizations.sql
- bento/crates/workflow/src/lib.rs
- compose.yml
> BM-616: TaskDB Optimizations

- .github/workflows/main.yml
- crates/boundless-cli/src/lib.rs
CI wasn't running any rust test on CI due to a wrong `ignored` keyword
> BM-665: Fix running tests on CI

- infra/order-stream/components/order-stream.ts
Another miss following the stack rename
> BM-749: Fix: request cert in prod based on stack rename

- documentation/site/pages/developers/smart-contracts/deployments.mdx
- documentation/site/pages/provers/quick-start.mdx
Note to provers to use our release branch.
Latest addresses for release.
> BM-766: Update addresses and note release branch

- justfile
Backported from other changes, was helpful when testing #526
> BM-780: spawn order stream in localnet

- crates/boundless-cli/src/bin/boundless-cli.rs
> BM-774: Fix stake balance formatting

- .github/CODEOWNERS
> Remove rlukata

- broker.toml
- crates/broker/src/config.rs
- **remove assumption_price**
- **add comments to broker.toml**
> BM-826: Add comments to explain parameters in broker.toml

- crates/broker/src/config.rs
- crates/indexer/tests/basic.rs
- offer.yaml
It also fixes a bug (previously missed by CI)
> BM-838: Update example offer.yaml to 0.1 HP

- .github/workflows/contracts.yml
- .github/workflows/documentation.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
A recent update of Foundry broke CI
> BM-849: pin foundry version on CI

- Cargo.lock
- crates/boundless-cli/Cargo.toml
- crates/boundless-cli/build.rs
- crates/boundless-cli/src/bin/boundless-cli.rs
- crates/boundless-cli/src/bin/boundless-ffi.rs
```console
boundless-cli --version
boundless-cli 0.7.0
branch:main
commit_hash:3c4d0920
build_time:2025-05-02 12:13:25 +01:00
build_env:rustc 1.85.1 (4eb161250 2025-03-15),1.85-aarch64-apple-darwin
```
> BM-805: Report git commit in boundless-cli --version

- crates/slasher/src/lib.rs
Should fix:
```console
thread 'main' panicked at /src/crates/slasher/src/lib.rs:427:14:
called `Option::unwrap()` on a `None` value
```
> BM-868: handle BlockTimestampNotFound

- crates/broker/src/db/mod.rs
- crates/broker/src/market_monitor.rs
Event delivery has at least once semantics. This was handled for RequestSubmitted event, but not for RequestLocked or RequestFulfilled. Extending support for those other events
> BM-880: Handle double event delivery in RequestSubmitted and RequestLocked

- broker.toml
- crates/broker/src/config.rs
- crates/broker/src/order_picker.rs
- documentation/site/pages/provers/broker.mdx
- infra/prover/broker-dev.toml
- infra/prover/broker-prod.toml
- infra/prover/broker-staging.toml
Is a DOS condition and has very unintended side effects like low pricing, so deleting and may come back with a different design later.
> BM-897: remove skip_preflight_ids config

- crates/broker/src/storage.rs
Similar to https://github.com/boundless-xyz/boundless/pull/593 but for orders
> BM-901: short circuit if prover has order image already

- infra/indexer/Pulumi.prod-11155111.yaml
- infra/indexer/Pulumi.staging.yaml
- infra/order-generator/Pulumi.prod.yaml
- infra/order-generator/Pulumi.staging.yaml
- infra/slasher/Pulumi.prod.yaml
- infra/slasher/Pulumi.staging.yaml
- infra/slasher/index.ts
Getting rate limited in the pipelines. Seems I forgot to add GH tokens to these packages
> BM-917: Add GH token to order gen, indexer, slasher

- crates/indexer/src/lib.rs
This PR addresses the starting block used when restarting the indexer to ensure that no gaps are created
> BM-937: Refactor starting block logic of Indexer

- infra/pipelines/pipelines/prover.ts
Should fix deployment error:
```
[Container] 2025/05/20 19:21:21.927273 Phase context status code: YAML_FILE_ERROR Message: mapping values are not allowed in this context at line 34
```
> BM-955: Fix buildspec for bento broker

- .github/workflows/main.yml
- documentation/site/pages/developers/steel/history.mdx
Not sure if this was what was intended or if it works, just trying to get CI to pass for #540
> BM-956: add rust check to docs CI changes and resolve issues

- crates/broker/src/bin/broker.rs
> BM-970: Fix Broker fillers

- infra/order-stream/components/order-stream.ts
For some reason the listener on the Base ALB was not updated in the last deployment. Trying this approach which adds both http and https listeners to see if it triggers an update. The http listener can be removed in a subsequent PR if this works.
> BM-976: Debug DNS, add both listeners

- infra/order-generator/Pulumi.staging-11155111.yaml
- infra/order-generator/Pulumi.staging-84532.yaml
- infra/prover/Pulumi.staging-11155111.yaml
- infra/prover/Pulumi.staging-84532.yaml
Updating prover and order generators with the new URLs
> Set new order stream urls

- infra/prover/components/bentoBroker.ts
- infra/prover/components/bonsaiBroker.ts
> Name fixes: 2

- crates/broker/src/order_monitor.rs
This check was accidentally removed as it was previously done implicitly in the DB call to get lockable orders. This causes orders to be locked immediately
> BM-1040: Fix broker locking/proving before target timestamp

- crates/broker/src/order_monitor.rs
> Backport target_timestamp fix to 0.9

- infra/indexer/components/rust-lambda.ts
Fixes issues where the log group isn't created before resources that depend on it are created. Also allows us to match the naming style of the log group to our other services.
> Create log group manually for lambda

- crates/broker/src/market_monitor.rs
- crates/broker/src/offchain_market_monitor.rs
- crates/broker/src/order_monitor.rs
- crates/broker/src/order_picker.rs
Few logs that are a bit noisy or duplicates of others
> BM-1045: lower noisy or duplicate log levels

- infra/order-stream/Pulumi.prod-84532.yaml
This triggers creation of the cert request. Step 1 for DNS. Also adds a missing GH token
> Request Base Sep Cert

- infra/order-stream/Pulumi.prod-84532.yaml
Cert has been validated. Enable its use.
> BM-1144: Use Base Sep Prod Cert

- crates/boundless-cli/src/bin/boundless.rs
- documentation/site/pages/developers/tooling/cli.mdx
- documentation/site/pages/developers/tutorials/request.mdx
- **updates to cli.mdx from review**
- **move module doc to long_about on CLI**
- **remove suggestion to use publicnode, as it will not always work**
- **suggested edits to requests page**
> Suggestions for #699

- infra/distributor/Pulumi.staging-84532.yaml
Draft until I check for any other issues
> BM-1264: fix distributor set verifier address on staging

- crates/broker/src/proving.rs
Gracefully handle this case, as it will be hit whenever a secondary fulfillment happens while the prover still fulfilling -- which shouldn't be marked as an error.
> BM-1271: gracefully handle external fulfillment case in proving

- Cargo.lock
- Cargo.toml
- crates/boundless-cli/src/bin/boundless-ffi.rs
- crates/boundless-cli/src/bin/boundless.rs
- crates/boundless-cli/src/lib.rs
- crates/boundless-market/src/client.rs
- crates/boundless-market/src/contracts/boundless_market.rs
- crates/boundless-market/src/order_stream_client.rs
- crates/guest/assessor/assessor-guest/Cargo.lock
- crates/indexer/tests/basic.rs
- crates/slasher/tests/basic.rs
- examples/composition/Cargo.lock
- examples/counter-with-callback/Cargo.lock
- examples/counter/Cargo.lock
- examples/smart-contract-requestor/Cargo.lock
- **BM-1307: Support fetching of ERC-1271 authorized requests in `boundless` cli (#890)**
- **Bump workspace version to 0.12.1**
> Cherry pick #890 to release-0.12

- crates/broker/src/lib.rs
- crates/broker/src/market_monitor.rs
- crates/broker/src/order_picker.rs
- crates/broker/src/proving.rs
> BM-1339: Cancel preflights when locked/fulfilled

- crates/broker/src/provers/bonsai.rs
https://github.com/risc0/risc0/blob/723813051d1d2d09a0b6721e1c05ad971f5c20ec/bento/crates/workflow/src/tasks/executor.rs#L353
> BM-1348: convert the execution limit to mi-cycles thought bonsai

- crates/broker/src/order_picker.rs
- justfile
Noticed while local testing a few things
> BM-1450: fix localnet env and misleading log

- crates/slasher/src/lib.rs
- crates/slasher/src/main.rs
- infra/slasher/Pulumi.prod-11155111.yaml
- infra/slasher/Pulumi.prod-8453.yaml
- infra/slasher/Pulumi.prod-84532.yaml
- infra/slasher/Pulumi.staging-11155111.yaml
- infra/slasher/Pulumi.staging-84532.yaml
- infra/slasher/index.ts
Issues when falling behind that large requests will fail.
> BM-1476: chunk slasher requests

- crates/broker/src/order_picker.rs
Very verbose with increased orders and makes it harder to read logs
> BM-1494: avoid debug logging all pending order IDs

- infra/order-stream/components/order-stream.ts
Currently has issues with rate limiting not resolving itself given tight limits and a 403 error code. This seems to be correct by Pulumi docs, but not certain
> BM-1510: Configure Order stream rate limiting response and policy

- .github/workflows/bento-release.yml
- .github/workflows/bento.yml
https://github.com/boundless-xyz/boundless/actions/runs/17414141776
> BM-1526: update bento and bento release CI

- scripts/setup.sh
update the setup script for ubuntu 24.04 and 22.04
> BM-1536: update the setup script

- .github/workflows/bento-release.yml
- compose.yml
- dockerfiles/agent.prebuilt.dockerfile
- dockerfiles/broker.prebuilt.dockerfile
- dockerfiles/rest_api.prebuilt.dockerfile
testing before setting up a better UX for building from source
> BM-1535: switch to use pre-build in compose.yml

- infra/order-generator/Pulumi.prod-8453.yaml
Temporary until provers upgrade, change intended to increase acceptance rate of more important orders
> BM-1565: reduce range of og cycles by 20% and slow interval

- bento/crates/workflow/src/tasks/executor.rs
Draft until tested on more cases and re-evaluate if there is another way around the try-deserialize each form
> BM-1615: Bento support for pvw prepare

- bento/crates/api/src/helpers.rs
- bento/crates/bento-client/src/bento_cli.rs
- compose.yml
- crates/boundless-cli/src/config.rs
- crates/broker/src/lib.rs
- crates/broker/src/provers/bonsai.rs
- dockerfiles/agent.prebuilt.dockerfile
- dockerfiles/bento_cli.dockerfile
- justfile
Still have to test the prepare/submit proofs through this, to ensure a 0 reservation job doesn't conflict with it.
> BM-1669: Auto-mining with unused capacity support
